// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqdMhWFSrJXXecmxfBg_g7nDIY1u1fD2k',
    appId: '1:713242272880:android:6009912e225e5ccfd200b5',
    messagingSenderId: '713242272880',
    projectId: 'grow-dev-flutter-fase-8',
    storageBucket: 'grow-dev-flutter-fase-8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpVz2NOKXupI3aQSoQbMSIvCZRwHiGQDQ',
    appId: '1:713242272880:ios:21b4f939f5522c2dd200b5',
    messagingSenderId: '713242272880',
    projectId: 'grow-dev-flutter-fase-8',
    storageBucket: 'grow-dev-flutter-fase-8.firebasestorage.app',
    androidClientId: '713242272880-9bptf74l2sgrkullulp4qiqpd8fgeck6.apps.googleusercontent.com',
    iosClientId: '713242272880-sn2g607o77ffd3tlqp3f9qvgvjcm968t.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialLoginNotification',
  );

}